name: Docker Image CI

on:
  push:
    branches:
      - interopnet
jobs:
  build-interop-6-16-0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          - ref: 'interop.6.16.0'
      - name: Create Dockerfile
        run: echo 'FROM archlinux:latest as builder
          RUN pacman -Syu --noconfirm opencl-icd-loader
          RUN pacman -S --noconfirm base-devel
          RUN pacman -Syu --noconfirm go gcc git bzr jq pkg-config opencl-icd-loader opencl-headers
          COPY . /lotus/
          WORKDIR /lotus
          RUN make clean && make all

          # This file is a template, and might need editing before it works on your project.

          FROM registry.cn-zhangjiakou.aliyuncs.com/wela/lotus:base
          #将编译好的程序从打包镜像中复制到运行镜像中
          COPY --from=builder /lotus/lotus   /usr/local/bin/
          COPY --from=builder /lotus/lotus-storage-miner  /usr/local/bin/
          COPY --from=builder /lotus/lotus-seal-worker /usr/local/bin/
          WORKDIR /lotus' >> Dockerfile
      - name: Login Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
      - name: Build and tag Docker images
        run: docker build -t ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interop.6.16.0 .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interop.6.16.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
      - name: Build and tag Docker images
        run: docker build -t ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
