name: Docker Image CI

on:
  push:
    branches:
      - interopnet

env:
  image: ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and tag Docker images
        run: docker build -t image:interopnet
      - name: Login Registry
        run:docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker image push
        run: docker push image:interopnet
