name: Docker Image CI

on:
  push:
    branches:
      - interopnet

env:
  image: ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo image
        run: echo $image && echo ${{image}}
      - name: Login Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
      - name: Build and tag Docker images
        run: docker build -t ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
      - name: Push image
        run: docker push ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
