name: Docker Image CI

on:
  push:
    branches:
      - interopnet
jobs:
  build-interop-6-16-0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: 'interop.6.16.0'
      - name: Create Dockrefile
        uses: echo 'test' >> Dockerfile
      - name: Login Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
      - name: Build and tag Docker images
        run: docker build -t ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interop.6.16.0 .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interop.6.16.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
      - name: Build and tag Docker images
        run: docker build -t ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_LOTUS_REPO}}:interopnet
